package Test_java;

import CaseStudyModule2JavaCore.Exception.NameException;

public class test2 {
    public static void main(String[] args) throws NameException {
        testException testException= new testException();
        testException.testthrow();
    }
}
